### ISSUE TITLE
Data for training

### ISSUE THREAD

**Issue by joaomario-brainly** [datumbox/datumbox-framework-zoo#1]
May I ask what data was used for training those models?
Thanks

**Comment by datumbox** [comment]
@joaomario-brainly Thanks for the question.

Unfortunately I won't be able to provide a satisfactory answer. The models have been trained many years ago using a collection of open-source public datasets (especially for sentiment and subjectivity analysis) AND scraped data from the web (wikipedia for language detection, websites from public directories for topic classification etc). In many cases the datasets have been mixed to provide a good enough coverage across different domains (especially for sentiment analysis across different types of reviews, feedback etc).

As I am not the owner of those datasets, I was not able to redistribute the "mixed versions" and that's why you won't find them referenced/provided on the website. I could give it a try to recover them from older backups but I would not hold my breath...

Thus sadly if you are after transparency (which in 2021 is a hot and important topic for ML), those models are not for you. I should also point out that these models are also from the statistical era of ML (prior 2012-2013) and thus I bet you can get better results using Deep Learning techniques. For state-of-the-art performance, I would recommend looking at one of the available Deep Learning frameworks.
